version: 2.1

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an environment ID and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: insert environment ID and flag key into demo code
          command: |
            sed -i.bak "s/environmentId *= *\".*\"/environmentId = \"${LD_HELLO_WORLD_ENV_ID}\"/" index.js
            sed -i.bak "s/featureFlagKey *= *\".*\"/featureFlagKey = \"${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}\"/" index.js
      - run: npm install
      - run:
          name: run demo
          command: |
            node index.js | tee output.txt
            grep "is true for this user" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
