name: CI

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.

jobs:
  verify-hello-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - run: npm i

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2.0.1
        with:
          use_client_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command: node index.js
